document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/\"><img src=\"https:\/\/musestar-silasila.github.io\/ms.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/\">首页<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/animation.html\">缪斯星动漫<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/movie.html\">缪斯星影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/app.html\">缪斯星软件<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-silasila.github.io\/muse.html\">缪斯星专区<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/musestar-silasila.github.io\/FAQ.html\" target=\"_blank\">投稿反馈<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/musestar-silasila.github.io\/pay.html\" target=\"_blank\">发电赞助<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/jq.qq.com\/?_wv=1027&k=4A08XieB\" target=\"_blank\">缪斯星官方QQ群<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");