document.write("<style type=\"text\/css\">");
document.write("    #box{");
document.write("        width: 380px;");
document.write("        margin: 30px auto;");
document.write("        font-family: 'Microsoft YaHei';");
document.write("        font-size: 14px;");
document.write("    }");
document.write("    input{");
document.write("        width: 260px;");
document.write("        border: 1px solid #e2e2e2;");
document.write("        height: 30px;");
document.write("        float: left;");
document.write("        background-image: url(images\/search.jpg);");
document.write("        background-repeat: no-repeat;");
document.write("        background-size: 25px;");
document.write("        background-position:5px center;");
document.write("        padding:0 0 0 40px;");
document.write("    }");
document.write("<\/style>");
document.write("    <div id=\"box\">");
document.write("<form class=\"navbar-form navbar-right site-search\" action=\"https:\/\/cn.bing.com\/search\" target=\"_blank\">");
document.write("  <div class=\"form-group\">");
document.write("    <input type=\"text\" class=\"form-control\" placeholder=\"搜索\" name=\"q\" value=\"                                                                                                                                                      site:musestar-silasila.github.io\">");
document.write("  <\/div>");
document.write("<button type=\"submit\" class=\"btn btn-default\">搜索<\/button><\/form>");
document.write("    <\/div>");