document.write(" <div class=\"blank\"><\/div>");
document.write("        <div class=\"botit\">");
document.write("          <h2>温馨提示<\/h2><\/div>");
document.write("        <div class=\"info\"><font color=\"red\">请勿相信视频内的任何广告<\/font><\/div>");
document.write("        <div class=\"info\"><font color=\"red\">请勿扫描播放器广告二维码<\/font><\/div>");
document.write("        <div class=\"info\"><font color=\"red\">问题反馈请点击右上角投稿反馈<\/font><\/div>");
document.write("      <\/div>");
document.write("         <\/div>");
document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("           <a href=\" https:\/\/musestar-silasila.github.io\">Copyright © 2014-2022 MUSESTAR All Rights Reserved<\/a><br>");
document.write("<a href=\"https:\/\/musestar-silasila.github.io\/icp.html\" target=\"_blank\">萌ICP备20220574号<\/a><br>");
document.write("<a href=\"https:\/\/musestar-silasila.github.io\/sitemap.xml\" target=\"_blank\">网站地图<\/a><br>");
document.write("           <a target=\"_blank\">本站只提供WEB页面服务，本站不存储、不制作任何视频，不承担任何由于内容的合法性及健康性所引起的争议和法律责任。<\/a>");